// Centralized content pulled from the live officialsunman.com so nothing is lost
// in the rebuild. Copy/URLs are easy to tweak here as the campaign evolves.

export const SITE = {
  name: "Sun-Man",
  tagline: "The original Black superhero. Over 40 years in the making.",
  contactEmail: "YlaSun1@gmail.com",
  creator: "Yla Eason",
};

export const NAV_LINKS = [
  { label: "About", href: "/about" },
  { label: "Gallery", href: "/gallery" },
  { label: "The Legend", href: "/legend" },
  { label: "Videos", href: "/videos" },
  { label: "Games", href: "/games" },
  { label: "Press", href: "/press" },
  { label: "Contact", href: "/contact" },
];

export type Retailer = {
  name: string;
  href: string;
  /** Set false to pull a retailer from the site without losing the link. */
  active?: boolean;
};

const ALL_RETAILERS: Retailer[] = [
  {
    // Delisted — flip back to true when stock returns.
    name: "Mattel",
    href: "https://www.mattel.com/products/masters-of-the-universe-origins-55-in-action-figure-assortment-hdr90",
    active: false,
  },
  {
    name: "Amazon",
    href: "https://www.amazon.com/Masters-Universe-Storytelling-10-Year-Olds-Collectors/dp/B09CLPY5PB/",
  },
  {
    // Delisted — flip back to true when stock returns.
    name: "Target",
    href: "https://www.target.com/p/masters-of-the-universe-origins-sun-man-action-figure/-/A-83766512",
    active: false,
  },
  {
    name: "Walmart",
    href: "https://www.walmart.com/ip/Masters-of-the-Universe-Origins-Sun-Man-5-5-In-Action-Figure-Battle-Figures-for-Storytelling-Play-and-Display/787560632",
  },
];

export const RETAILERS = ALL_RETAILERS.filter((r) => r.active !== false);

export const SOCIALS = [
  { name: "Instagram", href: "https://www.instagram.com/officialsunman/" },
  { name: "YouTube", href: "https://www.youtube.com/@officialsun-man7338" },
  { name: "TikTok", href: "https://www.tiktok.com/@officialsunman" },
  { name: "Facebook", href: "https://www.facebook.com/officialsunman/" },
  { name: "Threads", href: "https://www.threads.net/@officialsunman" },
];

// Legacy timeline — the throughline for both nostalgia fans and licensing execs.
// Dates/labels are placeholders where the live site did not state them; tweak freely.
export type Milestone = {
  year: string;
  title: string;
  body: string;
};

export const TIMELINE: Milestone[] = [
  {
    year: "1985",
    title: "A hero is created",
    body: "Yla Eason creates Sun-Man after her son says he can't be a superhero because he isn't white. She builds a hero whose power comes from his own skin.",
  },
  {
    year: "1985",
    title: "Olmec Toys is born",
    body: "Eason founds Olmec Toys to put Sun-Man on shelves — the first Black action figure with his own storyline and Royal African ancestry.",
  },
  {
    year: "2021",
    title: "Mattel brings him back",
    body: "Mattel, Olmec Toys, and YlaSun sign a licensing agreement to reintroduce Sun-Man for the first time since 1985, uniting Rulers of the Sun with Masters of the Universe.",
  },
  {
    year: "2022",
    title: "Toy Hall of Fame + Doll Legacy Award",
    body: "Sun-Man goes on display as MOTU is inducted into the Strong National Toy Hall of Fame, and Yla Eason wins the 2022 Doll Legacy Award.",
  },
  {
    year: "Today",
    title: "Over 40 years later",
    body: "The mission still stands: a Black child deserves to see himself as the hero. Sun-Man is on shelves worldwide and stepping into a new animated era.",
  },
];

// Press articles live in lib/press.ts and videos in lib/videos.ts — both are
// generated by tools/import-content.py from the Webflow exports.

// Image assets. The Webflow CDN blocks hotlinking (403 on every asset), so
// nothing is fetched remotely — everything is local under /public/img.
//
// To add an asset: drop the file in /public/img and set the path here. Any
// slot left `null` renders an <AssetSlot /> placeholder at the right aspect
// ratio, so layouts hold their shape until the real artwork lands.
export type ImageAsset = string | null;

export const ASSETS: Record<string, ImageAsset> = {
  // Full lockup: "Rulers of the Sun" + SUN-MAN.
  logo: "/img/sunman-logo.webp",
  // SUN-MAN only — tighter crop for the nav bar.
  wordmark: "/img/sunman-wordmark.webp",
  heroStill: null,
  ad1985: "/img/sun-man-advertisement-1985.webp",
};

/** The animated origin story, on the official YouTube channel. */
export const SERIES_VIDEO = {
  youtubeId: "x51UmtFXVBI",
  title: "The Legend of Sun-Man — Full Animated Origin Story",
  /** Local copy of the YouTube poster, so no frame loads from a remote host. */
  poster: "/img/series-poster.webp",
};

// The hero figure. Two assets:
//
// HERO_FIGURE  — the sharp static product shot (4421x4468 master), kept for the
//                fallback layout and for any still use.
// HERO_TURN    — a scroll-scrubbed turnaround, exported by
//                tools/process-hero-frames.py from sunman-turn-white.mp4 (the
//                white-backdrop render, ~4x sharper than the alpha master) with
//                the backdrop keyed out. See that script for why.
//
// WebP rather than AVIF: AVIF is ~40% smaller but fails on Safari < 16, and a
// blank hero is a worse trade than the extra weight.

export const YOUTUBE_CHANNEL = "https://www.youtube.com/@officialsun-man7338";

// The hero figure — a single transparent cutout, kept for the static fallback.
export const HERO_FIGURE = {
  src: "/img/hero-figure.webp",
  width: 2573,
  height: 2600,
};

// Largest height we can paint without upscaling on a 2x screen.
export const HERO_FIGURE_MAX_H = Math.floor(HERO_FIGURE.height / 2);

// Scroll-scrubbed turnaround, generated by tools/process-hero-frames.py from
// the white-backdrop master with the backdrop keyed out.
export const HERO_TURN = {
  count: 25,
  width: 1802,
  height: 1900,
  src: (i: number) => `/img/hero-turn/t${String(i + 1).padStart(2, "0")}.webp`,
};

/** Credibility markers shown above the hero headline. */
export const HERO_PROOF = [
  { value: "40+", label: "Years of legacy" },
  { value: "1985", label: "The original Black action figure" },
  { value: "Mattel", label: "Masters of the Universe" },
];

// Gallery images live in lib/gallery.ts (generated by tools/import-content.py).
