// Generated by tools/import-content.py from the Webflow gallery export.
// Images are local under /public/img/gallery — nothing is hotlinked.

// Real pixel dimensions travel with each image so the masonry
// tiles take the artwork's own shape — no letterboxing, no crop.
export type GalleryItem = {
  src: string;
  alt: string;
  width: number;
  height: number;
};

export const GALLERY: GalleryItem[] = [
  {
    src: "/img/gallery/digitino.webp",
    alt: "Digitino",
    width: 1400,
    height: 1049,
  },
  {
    src: "/img/gallery/digitino-2.webp",
    alt: "Digitino",
    width: 1400,
    height: 1049,
  },
  {
    src: "/img/gallery/digitino-2-3.webp",
    alt: "Digitino 2",
    width: 1400,
    height: 1049,
  },
  {
    src: "/img/gallery/digitino-latino-numerical-genius.webp",
    alt: "Digitino - Latino Numerical - Genius",
    width: 1400,
    height: 1049,
  },
  {
    src: "/img/gallery/flat-top-sun-man-space-sumo-pig-head.webp",
    alt: "Flat-Top Sun-Man - Space Sumo - Pig-Head",
    width: 1400,
    height: 1049,
  },
  {
    src: "/img/gallery/img-0426.webp",
    alt: "IMG 0426",
    width: 1170,
    height: 1157,
  },
  {
    src: "/img/gallery/img-0579.webp",
    alt: "IMG 0579",
    width: 1124,
    height: 1124,
  },
  {
    src: "/img/gallery/img-0580.webp",
    alt: "IMG 0580",
    width: 1143,
    height: 1143,
  },
  {
    src: "/img/gallery/img-0581.webp",
    alt: "IMG 0581",
    width: 1170,
    height: 1144,
  },
  {
    src: "/img/gallery/img-0582.webp",
    alt: "IMG 0582",
    width: 1170,
    height: 1162,
  },
  {
    src: "/img/gallery/img-0584.webp",
    alt: "IMG 0584",
    width: 1170,
    height: 1147,
  },
  {
    src: "/img/gallery/img-0586.webp",
    alt: "IMG 0586",
    width: 1170,
    height: 1148,
  },
  {
    src: "/img/gallery/img-8679.webp",
    alt: "IMG 8679",
    width: 1400,
    height: 1997,
  },
  {
    src: "/img/gallery/img-8708.webp",
    alt: "IMG 8708",
    width: 1400,
    height: 1050,
  },
  {
    src: "/img/gallery/img-8712.webp",
    alt: "IMG 8712",
    width: 1400,
    height: 1050,
  },
  {
    src: "/img/gallery/img-9504.webp",
    alt: "IMG 9504",
    width: 477,
    height: 477,
  },
  {
    src: "/img/gallery/olmec-ad-1992.webp",
    alt: "Olmec Ad 1992",
    width: 280,
    height: 167,
  },
  {
    src: "/img/gallery/olmec-toys-ad.webp",
    alt: "Olmec Toys Ad",
    width: 361,
    height: 400,
  },
  {
    src: "/img/gallery/pig-head.webp",
    alt: "Pig-Head",
    width: 1400,
    height: 1400,
  },
  {
    src: "/img/gallery/pig-head-front-stance.webp",
    alt: "Pig-Head Front Stance",
    width: 1400,
    height: 1049,
  },
  {
    src: "/img/gallery/pig-head-ready-for-battle.webp",
    alt: "Pig Head Ready For Battle",
    width: 1400,
    height: 1049,
  },
  {
    src: "/img/gallery/pig-head-retail-packaging.webp",
    alt: "Pig-Head Retail Packaging",
    width: 1400,
    height: 1400,
  },
  {
    src: "/img/gallery/secondary-sun-man.webp",
    alt: "Secondary Sun-Man",
    width: 780,
    height: 400,
  },
  {
    src: "/img/gallery/space-sumo-on-rock.webp",
    alt: "Space Sumo On Rock",
    width: 1400,
    height: 1049,
  },
  {
    src: "/img/gallery/space-sumo-standing.webp",
    alt: "Space Sumo Standing",
    width: 1400,
    height: 1049,
  },
  {
    src: "/img/gallery/sun-man-advertisement-1985.webp",
    alt: "Sun-Man Advertisement 1985",
    width: 685,
    height: 949,
  },
  {
    src: "/img/gallery/sun-man-afro-and-flat-top-digitino-space-sumo-pig-head.webp",
    alt: "Sun-Man  Afro And Flat Top - Digitino - Space Sumo- Pig-Head",
    width: 1400,
    height: 1049,
  },
  {
    src: "/img/gallery/sun-man-comic-cover-design.webp",
    alt: "Sun-Man Comic Cover Design",
    width: 1400,
    height: 2164,
  },
  {
    src: "/img/gallery/sun-man-front-hands-on-waist.webp",
    alt: "Sun-Man Front Hands On Waist",
    width: 1400,
    height: 1400,
  },
  {
    src: "/img/gallery/sun-man-front-view.webp",
    alt: "Sun-Man front View",
    width: 1400,
    height: 1400,
  },
  {
    src: "/img/gallery/sun-man-holding-sword-up.webp",
    alt: "Sun-Man holding sword up",
    width: 1400,
    height: 1400,
  },
  {
    src: "/img/gallery/sun-man-in-battle-pose.webp",
    alt: "Sun-Man In Battle Pose",
    width: 1400,
    height: 1049,
  },
  {
    src: "/img/gallery/sun-man-in-battle-pose-2.webp",
    alt: "Sun-Man In Battle Pose -2",
    width: 1400,
    height: 1049,
  },
  {
    src: "/img/gallery/sun-man-masterverse.webp",
    alt: "Sun-Man Masterverse",
    width: 1400,
    height: 1020,
  },
  {
    src: "/img/gallery/sun-man-motu-retail-packaging.webp",
    alt: "Sun-Man MOTU Retail Packaging",
    width: 1400,
    height: 1400,
  },
  {
    src: "/img/gallery/sun-man-pose-1.webp",
    alt: "Sun-Man Pose 1",
    width: 1400,
    height: 1550,
  },
  {
    src: "/img/gallery/sun-man-pose-2.webp",
    alt: "Sun-Man Pose 2",
    width: 1400,
    height: 1400,
  },
  {
    src: "/img/gallery/sun-man-pose-3.webp",
    alt: "Sun-Man Pose 3",
    width: 1400,
    height: 1400,
  },
  {
    src: "/img/gallery/sun-man-toy-package.webp",
    alt: "Sun-Man Toy Package",
    width: 1400,
    height: 1400,
  },
  {
    src: "/img/gallery/sun-man-with-accessories.webp",
    alt: "Sun-Man With Accessories",
    width: 1400,
    height: 1400,
  },
  {
    src: "/img/gallery/sun-man-withsword-and-shield-head-to-the-sky.webp",
    alt: "Sun-Man Withsword And Shield - Head To The Sky",
    width: 1400,
    height: 1400,
  },
  {
    src: "/img/gallery/tumblr.webp",
    alt: "Tumblr",
    width: 1080,
    height: 1080,
  },
  {
    src: "/img/gallery/unnamed.webp",
    alt: "Unnamed",
    width: 680,
    height: 680,
  },
  {
    src: "/img/gallery/unnamed-2.webp",
    alt: "Unnamed",
    width: 680,
    height: 680,
  },
  {
    src: "/img/gallery/unnamed-3.webp",
    alt: "Unnamed",
    width: 320,
    height: 180,
  },
  {
    src: "/img/gallery/unnamed-4.webp",
    alt: "Unnamed",
    width: 259,
    height: 194,
  },
  {
    src: "/img/gallery/unnamed-5.webp",
    alt: "Unnamed",
    width: 225,
    height: 225,
  },
  {
    src: "/img/gallery/unnamed-6.webp",
    alt: "Unnamed",
    width: 248,
    height: 204,
  },
  {
    src: "/img/gallery/unnamed-7.webp",
    alt: "Unnamed",
    width: 495,
    height: 323,
  },
  {
    src: "/img/gallery/unnamed-8.webp",
    alt: "Unnamed",
    width: 397,
    height: 512,
  },
];
