// Generated by tools/import-content.py from the Webflow press export.
// Images are local under /public/img/press — nothing is hotlinked.

export type PressItem = {
  title: string;
  publication: string;
  href: string;
  image: string;
  year: string;
};

export const PRESS: PressItem[] = [
  {
    title: "3-MINUTE BRIEFING: YLA EASON (MBA 1977)",
    publication: "Harvard Business School",
    href: "https://www.alumni.hbs.edu/stories/Pages/story-impact.aspx?num=8956",
    image: "/img/press/3-minute-briefing-yla-eason-mba-1977.webp",
    year: "2023",
  },
  {
    title: "Yla Eason, creator of Sun-Man and Owner of Olmec Toys",
    publication: "In The Doll World",
    href: "https://www.inthedollworld.com/yla-eason-creator-of-sun-man-and-owner-of-olmec-toys/",
    image: "/img/press/yla-eason-creator-of-sun-man-and-owner-of-olmec-toys.webp",
    year: "2023",
  },
  {
    title: "He-Man® and the Masters of the Universe®  Continues Expansion of Action Figure Line as Sun-Man™ Arrives at Global Retailers",
    publication: "Official Sun-Man",
    href: "https://www.officialsunman.com/press/he-man-r-and-the-masters-of-the-universe-r-continues-expansion-of-action-figure-line-as-sun-man-tm-arrives-at-global-retailers",
    image: "/img/press/he-man-r-and-the-masters-of-the-universe-r-continues-expansi.webp",
    year: "2022",
  },
  {
    title: "Here’s the story behind Sun-Man, the groundbreaking black action figure joining the ‘Masters of the Universe’ franchise",
    publication: "The Bharat Express News",
    href: "https://www.thebharatexpressnews.com/heres-the-story-behind-sun-man-the-groundbreaking-black-action-figure-joining-the-masters-of-the-universe-franchise/",
    image: "/img/press/heres-the-story-behind-sun-man-the-groundbreaking-black-acti.webp",
    year: "2022",
  },
  {
    title: "Here's the story behind Sun-Man, the groundbreaking Black action figure that's joining the 'Masters of the Universe' franchise",
    publication: "Yahoo",
    href: "https://www.yahoo.com/video/sun-man-he-man-masters-of-the-universe-yla-eason-rulers-of-the-sun-202415082.html",
    image: "/img/press/heres-the-story-behind-sun-man-the-groundbreaking-black-acti.webp",
    year: "2022",
  },
  {
    title: "Inspiration, Inclusion, and the Making of a Multicultural Toy Company",
    publication: "American Journal of Play | Winter & Spring 2021",
    href: "https://www.officialsunman.com/press/inspiration-inclusion-and-the-making-of-a-multicultural-toy-company",
    image: "/img/press/inspiration-inclusion-and-the-making-of-a-multicultural-toy-.webp",
    year: "2022",
  },
  {
    title: "Masters of the Universe: Origins Sun-Man Arrives from Mattel",
    publication: "Bleeding Cool",
    href: "https://bleedingcool.com/collectibles/masters-of-the-universe-origins-sun-man-arrives-from-mattel/",
    image: "/img/press/masters-of-the-universe-origins-sun-man-arrives-from-mattel.webp",
    year: "2022",
  },
  {
    title: "Mattel Announces MOTU Origins Rulers of the Sun Figure Line: Sun-Man Pre-Orders are Live",
    publication: "ComicBook",
    href: "https://comicbook.com/gear/news/mattel-announces-motu-origins-rulers-of-the-sun-figure-line-sun-man-pre-orders-are-live/",
    image: "/img/press/mattel-announces-motu-origins-rulers-of-the-sun-figure-line-.webp",
    year: "2022",
  },
  {
    title: "Mattel Brings Back “Rulers of the Sun” to the “Masters of the Universe” Toy Line in 2022 – Sun-Man Available for Preorder",
    publication: "LaughingPlace",
    href: "https://www.laughingplace.com/w/articles/2022/02/01/mattel-sun-man-rulers-of-the-sun-2022-toy-line-announcement/",
    image: "/img/press/mattel-brings-back-rulers-of-the-sun-to-the-masters-of-the-u.webp",
    year: "2022",
  },
  {
    title: "Mattel ‘s He-Man® and the Masters of the Universe® Continues Expansion of Action Figure Line as Sun-Man™ Arrives at Global Retailers #MOTU",
    publication: "Action Figure Insider",
    href: "http://www.actionfigureinsider.com/mattel-s-he-man-and-the-masters-of-the-universe-continues-expansion-of-action-figure-line-as-sun-man-arrives-at-global-retailers-motu/",
    image: "/img/press/mattel-s-he-man-r-and-the-masters-of-the-universe-r-continue.webp",
    year: "2022",
  },
  {
    title: "Pioneering Creator of Black Superhero Figure Sees Trend Toward Futuristic Toys and Media for Children of Color",
    publication: "Rutgers University–Newark",
    href: "https://www.newark.rutgers.edu/news/pioneering-creator-black-superhero-figure-sees-trend-toward-futuristic-toys-and-media-children",
    image: "/img/press/pioneering-creator-of-black-superhero-figure-sees-trend-towa.webp",
    year: "2022",
  },
  {
    title: "Sun-Man and the Rulers of the Sun Are Back for Real",
    publication: "Gizmodo",
    href: "https://gizmodo.com/sun-man-he-man-masters-of-the-universe-toys-revealed-1848455109",
    image: "/img/press/sun-man-and-the-rulers-of-the-sun-are-back-for-real.webp",
    year: "2022",
  },
  {
    title: "Sun-Man Creator Yla Eason Reflects on the Rulers of the Sun Joining He-Man and the Masters of the Universe",
    publication: "Complex",
    href: "https://www.complex.com/pop-culture/yla-eason-sun-man-masters-of-the-universe-interview/",
    image: "/img/press/sun-man-creator-yla-eason-reflects-on-the-rulers-of-the-sun-.webp",
    year: "2022",
  },
  {
    title: "Sun-Man Joins He-Man's Iconic Origins Toy Line as Masters of the Universe Turns 40",
    publication: "IGN",
    href: "https://www.ign.com/articles/sun-man-masters-of-the-universe-announcement-creator-interview",
    image: "/img/press/sun-man-joins-he-mans-iconic-origins-toy-line-as-masters-of-.webp",
    year: "2022",
  },
  {
    title: "Yla Eason Interview - Sun-Man: Masters of the Universe",
    publication: "Screen Rant",
    href: "https://screenrant.com/sun-man-masters-universe-toys-yla-eason-interview/",
    image: "/img/press/yla-eason-interview-sun-man-masters-of-the-universe.webp",
    year: "2022",
  },
  {
    title: "He-Man gets a new partner: Sun-Man, a pioneering Black superhero toy",
    publication: "CNET",
    href: "http://cnet.com",
    image: "/img/press/he-man-gets-a-new-partner-sun-man-a-pioneering-black-superhe.webp",
    year: "2021",
  },
  {
    title: "Mattel dusts off He-Man, with a nod to diversity.",
    publication: "The New York Times",
    href: "https://www.nytimes.com/2021/09/10/business/mattel-he-man-masters-of-the-universe.html",
    image: "/img/press/mattel-dusts-off-he-man-with-a-nod-to-diversity.webp",
    year: "2021",
  },
  {
    title: "Professor's Pioneering Black Superhero is Reintroduced by Mattel",
    publication: "Rutgers Business School",
    href: "https://www.business.rutgers.edu/news/professors-pioneering-black-superhero-reintroduced-mattel",
    image: "/img/press/professors-pioneering-black-superhero-is-reintroduced-by-mat.webp",
    year: "2021",
  },
  {
    title: "Sun-Man Joins The Masters Of The Universe, Figure On Sale Monday",
    publication: "Bleeding Cool",
    href: "http://bleedingcool.com",
    image: "/img/press/sun-man-joins-the-masters-of-the-universe-figure-on-sale-mon.webp",
    year: "2021",
  },
  {
    title: "Sun-Man Revived: Meet A Pioneer of Multicultural Superheroes",
    publication: "The Christian Science Monitor",
    href: "https://www.csmonitor.com/The-Culture/2021/1223/Sun-Man-revived-Meet-a-pioneer-of-multicultural-superheroes",
    image: "/img/press/sun-man-revived-meet-a-pioneer-of-multicultural-superheroes.webp",
    year: "2021",
  },
  {
    title: "Black Toys R Us",
    publication: "MSNBC",
    href: "https://www.msnbc.com/podcast/black-toys-r-us-n1252302",
    image: "/img/press/black-toys-r-us.webp",
    year: "2020",
  },
];
