#!/usr/bin/env python3
"""Import press articles and YouTube videos from the Webflow CSV exports.

Images are downloaded and re-encoded locally — nothing is hotlinked, matching
the rest of the site. Writes lib/press.ts and lib/videos.ts.

Usage: python3 tools/import-content.py
"""
import csv, os, re, urllib.request, urllib.parse
from datetime import datetime
from PIL import Image
from io import BytesIO

HOME = os.path.expanduser("~/Downloads")
PRESS_CSV  = f"{HOME}/Official Sunman - Press - 6582ee9ff3adf1e5adee7551.csv"
VIDEO_CSV  = f"{HOME}/Official Sunman - YouTube Videos - 69624f5f73e3facf8cb86589 (1).csv"
GALLERY_CSV = f"{HOME}/Official Sunman - Gallery Images - 6582ee9ff3adf1e5adee7552.csv"
UA = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/120 Safari/537.36"}

def fetch(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=45).read()

def save_webp(data, path, width, quality=82):
    im = Image.open(BytesIO(data))
    im = im.convert("RGB") if im.mode in ("P", "RGBA", "LA") else im.convert("RGB")
    if im.width > width:
        im = im.resize((width, round(im.height * width / im.width)), Image.LANCZOS)
    im.save(path, "WEBP", quality=quality, method=6)
    return im.size

def ts(s):  # escape for a TypeScript double-quoted string
    return s.replace("\\", "\\\\").replace('"', '\\"').strip()

# The export leaves Publication blank on some rows; fall back to the domain,
# but render known outlets with their proper name.
OUTLETS = {
    "alumni.hbs.edu": "Harvard Business School",
    "business.rutgers.edu": "Rutgers Business School",
    "newark.rutgers.edu": "Rutgers University–Newark",
    "inthedollworld.com": "In The Doll World",
    "thebharatexpressnews.com": "The Bharat Express News",
    "thisislovepodcast.com": "This Is Love",
    "cnet.com": "CNET",
    "nytimes.com": "The New York Times",
    "ign.com": "IGN",
    "gizmodo.com": "Gizmodo",
    "complex.com": "Complex",
    "screenrant.com": "Screen Rant",
    "bleedingcool.com": "Bleeding Cool",
    "comicbook.com": "ComicBook",
    "laughingplace.com": "LaughingPlace",
    "actionfigureinsider.com": "Action Figure Insider",
    "yahoo.com": "Yahoo",
    "msnbc.com": "MSNBC",
    "csmonitor.com": "The Christian Science Monitor",
    "officialsunman.com": "Official Sun-Man",
}

def pretty(name, url):
    n = (name or "").strip()
    h = host_of(url)
    if not n or "." in n:                 # blank, or the export stored a domain
        return OUTLETS.get(h, OUTLETS.get(host_of(n) if n else "", n or h))
    return n

def host_of(url):
    try:
        h = urllib.parse.urlparse(url).netloc.replace("www.", "")
        return h or ""
    except Exception:
        return ""

def year_of(s):
    m = re.search(r"\b(19|20)\d{2}\b", s or "")
    return m.group(0) if m else ""

# ---------------------------------------------------------------- press
def do_press():
    os.makedirs("public/img/press", exist_ok=True)
    rows = list(csv.DictReader(open(PRESS_CSV, encoding="utf-8-sig")))
    items = []
    for r in rows:
        if (r.get("Blog") or "").lower() == "true":
            continue                                  # blog posts, not press
        img, link = r.get("Featured Image"), r.get("Publication Link")
        if not img or not link:
            continue
        slug = r["Slug"][:60]
        out = f"public/img/press/{slug}.webp"
        if not os.path.exists(out):
            try:
                size = save_webp(fetch(img), out, 900)
                print(f"  ✓ {slug[:44]:46} {size[0]}x{size[1]}")
            except Exception as e:
                print(f"  ✗ {slug[:44]:46} {e}")
                continue
        items.append({
            "title": r["Article Name"].strip(),
            "publication": pretty(r.get("Publication"), link),
            "href": link.strip(),
            "image": f"/img/press/{slug}.webp",
            "year": year_of(r.get("Published Date") or r.get("Created On")),
        })
    items.sort(key=lambda i: i["year"], reverse=True)
    with open("lib/press.ts", "w") as f:
        f.write("// Generated by tools/import-content.py from the Webflow press export.\n"
                "// Images are local under /public/img/press — nothing is hotlinked.\n\n"
                "export type PressItem = {\n  title: string;\n  publication: string;\n"
                "  href: string;\n  image: string;\n  year: string;\n};\n\n"
                "export const PRESS: PressItem[] = [\n")
        for i in items:
            f.write("  {\n"
                    f'    title: "{ts(i["title"])}",\n'
                    f'    publication: "{ts(i["publication"])}",\n'
                    f'    href: "{ts(i["href"])}",\n'
                    f'    image: "{i["image"]}",\n'
                    f'    year: "{i["year"]}",\n'
                    "  },\n")
        f.write("];\n")
    print(f"  -> lib/press.ts: {len(items)} articles")

# Videos that aren't in the Webflow export. Listed here so re-running the
# import doesn't drop them; remove one once it appears in the CSV.
MANUAL_VIDEOS = [
    {"id": "GCxwqZfCsSE", "title": "Sun-Man", "channel": "Official Sun-Man",
     "channel_url": "https://www.youtube.com/@officialsun-man7338", "duration": ""},
]

# ---------------------------------------------------------------- videos
def do_videos():
    os.makedirs("public/img/videos", exist_ok=True)
    rows = [
        {"Video Title": m["title"], "Video ID": m["id"], "Channel": m["channel"],
         "Channel link": m["channel_url"], "Duration": m["duration"]}
        for m in MANUAL_VIDEOS
    ] + list(csv.DictReader(open(VIDEO_CSV, encoding="utf-8-sig")))
    items, seen = [], set()
    for r in rows:
        vid = (r.get("Video ID") or "").strip()
        if not vid or vid in seen:
            continue
        seen.add(vid)
        out = f"public/img/videos/{vid}.webp"
        if not os.path.exists(out):
            got = False
            for q in ("maxresdefault", "hqdefault"):
                try:
                    save_webp(fetch(f"https://i.ytimg.com/vi/{vid}/{q}.jpg"), out, 640)
                    got = True; break
                except Exception:
                    continue
            if not got:
                print(f"  ✗ no thumbnail for {vid}")
                continue
        dur = (r.get("Duration") or "").strip()
        # the export writes some durations as H:MM:SS where it means MM:SS
        if dur.endswith(":00") and dur.count(":") == 2:
            dur = ":".join(dur.split(":")[:2])
        items.append({
            "title": r["Video Title"].strip(),
            "youtubeId": vid,
            "channel": (r.get("Channel") or "").strip(),
            "channelUrl": (r.get("Channel link") or "").strip(),
            "duration": dur,
            "thumb": f"/img/videos/{vid}.webp",
        })
    with open("lib/videos.ts", "w") as f:
        f.write("// Generated by tools/import-content.py from the Webflow YouTube export.\n"
                "// Thumbnails are local under /public/img/videos — nothing is hotlinked.\n\n"
                "export type VideoItem = {\n  title: string;\n  youtubeId: string;\n"
                "  channel: string;\n  channelUrl: string;\n  duration: string;\n  thumb: string;\n};\n\n"
                "export const VIDEOS: VideoItem[] = [\n")
        for i in items:
            f.write("  {\n"
                    f'    title: "{ts(i["title"])}",\n'
                    f'    youtubeId: "{i["youtubeId"]}",\n'
                    f'    channel: "{ts(i["channel"])}",\n'
                    f'    channelUrl: "{ts(i["channelUrl"])}",\n'
                    f'    duration: "{i["duration"]}",\n'
                    f'    thumb: "{i["thumb"]}",\n'
                    "  },\n")
        f.write("];\n")
    print(f"  -> lib/videos.ts: {len(items)} videos")

# ---------------------------------------------------------------- gallery
def do_gallery():
    os.makedirs("public/img/gallery", exist_ok=True)
    rows = list(csv.DictReader(open(GALLERY_CSV, encoding="utf-8-sig")))
    items, seen = [], set()
    for r in rows:
        url = (r.get("Image") or "").strip()
        if not url or url in seen:
            continue                                   # the export repeats some shots
        seen.add(url)
        slug = re.sub(r"[^a-z0-9]+", "-", (r.get("Slug") or "").lower()).strip("-")[:56]
        out = f"public/img/gallery/{slug}.webp"
        if not os.path.exists(out):
            try:
                w, h = save_webp(fetch(url), out, 1400, quality=80)
            except Exception as e:
                print(f"  x {slug[:40]:42} {e}")
                continue
        else:
            w, h = Image.open(out).size
        items.append({
            "src": f"/img/gallery/{slug}.webp",
            "alt": (r.get("Name") or "Sun-Man").strip(),
            "width": w,
            "height": h,
        })
    with open("lib/gallery.ts", "w") as f:
        f.write("// Generated by tools/import-content.py from the Webflow gallery export.\n"
                "// Images are local under /public/img/gallery — nothing is hotlinked.\n\n"
                "// Real pixel dimensions travel with each image so the masonry\n"
                "// tiles take the artwork's own shape — no letterboxing, no crop.\n"
                "export type GalleryItem = {\n  src: string;\n  alt: string;\n"
                "  width: number;\n  height: number;\n};\n\n"
                "export const GALLERY: GalleryItem[] = [\n")
        for i in items:
            f.write("  {\n"
                    f'    src: "{i["src"]}",\n'
                    f'    alt: "{ts(i["alt"])}",\n'
                    f'    width: {i["width"]},\n'
                    f'    height: {i["height"]},\n'
                    "  },\n")
        f.write("];\n")
    print(f"  -> lib/gallery.ts: {len(items)} images")

if __name__ == "__main__":
    print("press:");   do_press()
    print("videos:");  do_videos()
    print("gallery:"); do_gallery()
